### PR TITLE
Add google analytics

### PR DESCRIPTION
**Pull request by witchy-mutant**

### CODE REVIEW

**Comment by ptrstpp950** [comment]
Still nothing is visible

**Comment by kkokosa** [comment]
Google needs some time to kick-off, I believe we will see something in few hours or tommorow :)

**Comment by ptrstpp950** [comment]
@mihcall will you delete branch now?

**Comment by witchy-mutant** [comment]
I see it already, I let you know guys that we can close the issue after it recorded my first visit :)

**Comment by witchy-mutant** [comment]
and yes, branch is deleted

**Pull request merged**
