### PR TITLE
added logo to the page for a good start 

### PR DESCRIPTION
**Pull request by abenedykt**
the image is from this site http://simpleicon.com/loudspeaker.html it appears that its free to use

### CODE REVIEW

**Comment by ptrstpp950** [comment]
Why you add link to http://simpleicon.com/wp-content/uploads/loudspeaker.svg instead of local file?

**Comment by abenedykt** [comment]
fixed :)

**Comment by kkokosa** [comment]
Maybe we should place this logo closer to the title? Now it looks as placed at some slightly random place for me:)

**Comment by ptrstpp950** [comment]
Do it :)

wt., 24.11.2015 o 10:40 użytkownik Konrad Kokosa notifications@github.com
napisał:

**Comment by ptrstpp950** [comment]
I fixed it :)

**Comment by abenedykt** [comment]
nice ;) +1

**Comment by kkokosa** [comment]
Nice :)

**Comment by abenedykt** [comment]
taking about ui, what about adding _.table-striped_ on table to get colored rows?

**Comment by ptrstpp950** [comment]
I just checked this and looks cool. What do you think @kkokosa ?

**Comment by kkokosa** [comment]
I think we can for now, as the very first prototype had colored rows and it looked ok. In the future we will probably style things a little bit further probably:)

**Comment by ptrstpp950** [comment]
Did it :)

**Comment by kkokosa** [comment]
Nice:)

**Pull request merged**
