### PR TITLE
Added DDDScotlandCFP

### PR DESCRIPTION
**Pull request by gep13**

### CODE REVIEW

**Comment by gep13** [comment]
@cmatskas any chance you can have a look at this? Thanks!

**Comment by cmatskas** [comment]
Done! Thank you for your contribution :)

**Comment by gep13** [comment]
@cmatskas thank you very much! :+1:

**Comment by ptrstpp950** [comment]
@gep13 we should thank you :+1:

**Comment by cmatskas** [comment]
@ptrstpp950 I did :)

**Pull request merged**
