### PR TITLE
New conferences added

### PR DESCRIPTION
**Pull request by cmatskas**
As per the title

### CODE REVIEW

**Comment by ptrstpp950** [comment]
I think we should add tags. Without it I don't know topic of the conferences

**Comment by cmatskas** [comment]
It makes sense.. I will add them tonight and push again

**Comment by ptrstpp950** [comment]
I will try to add tags to previous ones

**Comment by ptrstpp950** [comment]
I added tags to previous CFP and fix dates. Could you change your parser to create dates with leading zeros (for example: like 2016-01-04 instead of 2016-1-4)

**Comment by cmatskas** [comment]
Will do :) first task of the year!!! OSS FTW 

Sent from Outlook Mobile

On Fri, Jan 1, 2016 at 10:05 AM -0800, "Piotr Stapp" notifications@github.com wrote:

I added tags to previous CFP and fix dates. Could you change your parser to create dates with leading zeros (for example: like 2016-01-04 instead of 2016-1-4)

**Comment by cmatskas** [comment]
Hi @ptrstpp950 I fixed the parser. Do I still need to include tags or did you fix these too? Keen to get this first PR of the year sorted :)

**Comment by ptrstpp950** [comment]
I added tags manually. I don't have an idea how to add them automatically

**Comment by cmatskas** [comment]
I meant is there anything left to be done for this PR?

**Comment by ptrstpp950** [comment]
Yes. I fixed tags for old CFP from previous bundle. In this bundle I didn't do anythibg

**Comment by cmatskas** [comment]
Gotcha! I'll fix it then. Thanks

Sent from Outlook Mobile

On Sat, Jan 2, 2016 at 3:39 AM -0800, "Piotr Stapp" notifications@github.com wrote:

Yes. I fixed tags for old CFP from previous bundle. In this bundle I didn't do anythibg

**Comment by cmatskas** [comment]
@ptrstpp950 ready for merging :)

**Pull request merged**
