### PR TITLE
Added favicon

### PR DESCRIPTION
**Pull request by cmatskas**
As per issue #8

### CODE REVIEW

**Comment by cmatskas** [comment]
Can you guys see the da icon? I'm on a mobile browser so can't verify it worked :)

**Comment by cmatskas** [comment]
Da icon === favicon

**Comment by ptrstpp950** [comment]
it is visible, but it has a white background. It should be transparent. like github or inbox incon

**Comment by cmatskas** [comment]
Right? I'll work to get a better one tonight :)

**Comment by ptrstpp950** [comment]
I will fix it

**Comment by cmatskas** [comment]
I lick the tools so you're more than welcome. I should have checked but I was in the office  lucking the appropriate tooling :(

**Comment by ptrstpp950** [comment]
fixed with visual studio and https://cloudconvert.com/svg-to-ico

**Pull request merged**
